### ISSUE TITLE
Still AUTH issues

### ISSUE THREAD

**Issue by ukdtom** [vanstinator/UASViewer.bundle#3]
Heh....Found the cause ;-)

In your default prefs file, the WebTools port is set to 32400

Humbly suggest you change that to 33400

/T

**Comment by ukdtom** [comment]
Also suggest, that you do NOT use localhost, but instead hardcode 127.0.0.1

localhost doesn't exists on all platforms

**Comment by vanstinator** [comment]
Yeah it's also because WebTools starts after this does. (the port is a preference that can be changed, as is localhost. That said I've already switched the default port)

**Comment by vanstinator** [comment]
Note to self: If login fails due to WebTools not loading right away we need to silently fall back so other channels can load and try again in a few seconds.

**Comment by ukdtom** [comment]
You missed the point here......

Your channel is running on the PMS, so why have the IP/Host name in the prefs?

Use a hardcoded http://127.0.0.1, cuz that will ALWAYS work

/T

**Comment by vanstinator** [comment]
*lightbulb.

That makes much more sense :) I'm so used to adding an IP address option to everything it didn't occur to me I didn't need it yet. I've been working on this in bits and pieces of free time so I've been a bit rushed when writing it and haven't sat down and done a real code review yet either.

Thanks for looking over all of this stuff for me, I really appreciate it.
